# Generated by Django 3.2 - Optimized Users Table Migration

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                # Authentication fields from AbstractBaseUser
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                
                # Permission fields from PermissionsMixin
                ('is_superuser', models.BooleanField(
                    default=False, 
                    help_text='Designates that this user has all permissions without explicitly assigning them.', 
                    verbose_name='superuser status'
                )),
                
                # Custom User fields
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150, blank=False)),
                ('last_name', models.CharField(max_length=150, blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                
                # ManyToMany relationships
                ('groups', models.ManyToManyField(
                    blank=True,
                    help_text='The groups this user belongs to.',
                    related_name='ats_gateway_user_set',
                    related_query_name='user',
                    to='auth.Group',
                    verbose_name='groups',
                )),
                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    help_text='Specific permissions for this user.',
                    related_name='ats_gateway_user_set',
                    related_query_name='user',
                    to='auth.Permission',
                    verbose_name='user permissions',
                )),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        
        # Add indexes for better performance
        migrations.RunSQL(
            """
            CREATE INDEX idx_users_public_id ON users(public_id);
            CREATE INDEX idx_users_is_active ON users(is_active);
            CREATE INDEX idx_users_date_joined ON users(date_joined);
            CREATE INDEX idx_users_is_staff ON users(is_staff);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_users_public_id;
            DROP INDEX IF EXISTS idx_users_is_active;
            DROP INDEX IF EXISTS idx_users_date_joined;
            DROP INDEX IF EXISTS idx_users_is_staff;
            """
        ),
    ] 