# Generated by Django 3.2 - Create Scanning Algorithm Table

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # No dependencies since this is a foundational table
    ]

    operations = [
        # Create ScanningAlgorithm table
        migrations.CreateModel(
            name='ScanningAlgorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, db_index=True)),
                ('display_name', models.CharField(max_length=255, db_index=True, null=True, blank=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('parameters_schema', models.JSONField(default=dict, blank=True, help_text='Algorithm configuration parameters')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scanning Algorithm',
                'verbose_name_plural': 'Scanning Algorithms',
                'db_table': 'scanning_algorithms',
                'ordering': ['name'],
            },
        ),

        # Add performance indexes for scanning_algorithms table
        migrations.RunSQL(
            """
            -- Indexes for scanning_algorithms
            CREATE INDEX idx_scanning_algorithms_name ON scanning_algorithms(name);
            CREATE INDEX idx_scanning_algorithms_is_active ON scanning_algorithms(is_active);
            CREATE INDEX idx_scanning_algorithms_created_at ON scanning_algorithms(created_at);
            CREATE INDEX idx_scanning_algorithms_display_name ON scanning_algorithms(display_name);
            """,
            reverse_sql="""
            -- Drop indexes for scanning_algorithms
            DROP INDEX IF EXISTS idx_scanning_algorithms_name;
            DROP INDEX IF EXISTS idx_scanning_algorithms_is_active;
            DROP INDEX IF EXISTS idx_scanning_algorithms_created_at;
            DROP INDEX IF EXISTS idx_scanning_algorithms_display_name;
            """
        ),
    ] 