# Generated by Django 3.0 on 2023-03-09 15:36

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_mysql.models.EnumField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('exicuted', 'exicuted')], default='pending'),
        ),
    ]
