# Generated by Django 3.2 - Create Initiation Algorithm Table

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0001_create_scanning_algorithm'),
    ]

    operations = [
        # Create InitiationAlgorithm table
        migrations.CreateModel(
            name='InitiationAlgorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, db_index=True)),
                ('display_name', models.CharField(max_length=255, db_index=True, null=True, blank=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Initiation Algorithm',
                'verbose_name_plural': 'Initiation Algorithms',
                'db_table': 'initiation_algorithms',
                'ordering': ['name'],
            },
        ),

        # Add performance indexes for initiation_algorithms table
        migrations.RunSQL(
            """
            -- Indexes for initiation_algorithms
            CREATE INDEX idx_init_algo_name ON initiation_algorithms(name);
            CREATE INDEX idx_init_algo_active ON initiation_algorithms(is_active);
            CREATE INDEX idx_init_algo_created ON initiation_algorithms(created_at);
            CREATE INDEX idx_init_algo_display ON initiation_algorithms(display_name);
            """,
            reverse_sql="""
            -- Drop indexes for initiation_algorithms
            DROP INDEX IF EXISTS idx_init_algo_name;
            DROP INDEX IF EXISTS idx_init_algo_active;
            DROP INDEX IF EXISTS idx_init_algo_created;
            DROP INDEX IF EXISTS idx_init_algo_display;
            """
        ),
    ] 