# Generated by Django 2.2 on 2023-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(auto_created=True, default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.CharField(auto_created=True, default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.CharField(auto_created=True, default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='id',
            field=models.CharField(auto_created=True, default='', max_length=64, primary_key=True, serialize=False),
        ),
    ]
