# Generated by Django 3.2 on 2023-09-19 18:48

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('tracking', 'TRACKING'), ('scanning', 'SCANNING')], default='tracking', max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'algorithm',
                'verbose_name_plural': 'algorithms',
                'db_table': 'algorithms',
            },
        ),
        migrations.RenameField(
            model_name='tradesession',
            old_name='is_closed',
            new_name='dummy',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trading_alog_id',
        ),
        migrations.RemoveField(
            model_name='tradesession',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='tradesession',
            name='scanning_alogo_id',
        ),
        migrations.AddField(
            model_name='order',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='frictional_losses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kite_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='1', max_length=64),
        ),
        migrations.AddField(
            model_name='trade',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_id',
            field=models.CharField(default='1', max_length=64),
        ),
        migrations.AddField(
            model_name='trade',
            name='view',
            field=django_mysql.models.EnumField(choices=[('long', 'long'), ('short', 'short')], default='long'),
        ),
        migrations.AddField(
            model_name='tradesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradesession',
            name='user_id',
            field=models.CharField(default='1', max_length=64),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='id',
            field=models.CharField(auto_created=True, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Slto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.order')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.trade')),
            ],
            options={
                'db_table': 'algo_slto_track_records',
            },
        ),
        migrations.CreateModel(
            name='AlgoUdtsScanRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resistence_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_strength', models.DecimalField(decimal_places=4, max_digits=10)),
                ('resistence_strength', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_trend', models.CharField(choices=[('bullish', 'BULLISH'), ('bearish', 'BEARISH')], default='bullish', max_length=20)),
                ('trade_candle_interval', models.CharField(max_length=255)),
                ('movement_potential', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.trade')),
            ],
            options={
                'db_table': 'algo_udts_scan_records',
            },
        ),
        migrations.AddField(
            model_name='tradesession',
            name='scanning_algorithm',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'scanning'}, on_delete=django.db.models.deletion.CASCADE, related_name='scanning_sessions', to='trade_management_unit.algorithm'),
        ),
        migrations.AddField(
            model_name='tradesession',
            name='tracking_algorithm',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'tracking'}, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='trade_management_unit.algorithm'),
        ),
    ]
