# Generated by Django 4.0.7 on 2023-02-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.stock', verbose_name='Traded Stock')),
            ],
            options={
                'db_table': 'trades',
            },
        ),
    ]
