# Generated by Django 4.0.7 on 2023-02-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0002_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
