# Generated by Django 3.0 on 2023-03-09 15:40

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0002_auto_20230309_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=django_mysql.models.EnumField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy'),
            preserve_default=False,
        ),
    ]
