# Generated by Django 2.2 on 2023-03-09 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0002_auto_20230309_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='startted_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.Stock', verbose_name='stock_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.Trade', verbose_name='trade_id'),
        ),
    ]
