# Generated by Django 3.2 - Create Instruments Table

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0003_create_termination_algorithm'),
    ]

    operations = [
        # Create Instrument table
        migrations.CreateModel(
            name='Instrument',
            fields=[
                # Use BigIntegerField for instrument ID (from broker)
                ('id', models.BigIntegerField(primary_key=True, serialize=False, help_text='Broker-provided instrument ID')),
                
                # Broker-specific identifiers
                ('instrument_token', models.BigIntegerField(unique=True, db_index=True, help_text='Unique instrument token from broker')),
                ('exchange_token', models.BigIntegerField(db_index=True, help_text='Exchange-specific token')),
                
                # Basic instrument information
                ('trading_symbol', models.CharField(max_length=200, db_index=True, help_text='Trading symbol (e.g., RELIANCE)')),
                ('name', models.CharField(max_length=200, db_index=True, help_text='Full instrument name')),
                
                # Price and trading information
                ('last_price', models.DecimalField(max_digits=12, decimal_places=2, help_text='Last traded price')),
                ('tick_size', models.DecimalField(max_digits=10, decimal_places=4, help_text='Minimum price movement')),
                ('lot_size', models.IntegerField(help_text='Trading lot size')),
                
                # Options/Futures specific fields
                ('expiry', models.DateField(null=True, blank=True, help_text='Expiry date for derivatives')),
                ('strike', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True, help_text='Strike price for options')),
                
                # Classification fields
                ('instrument_type', models.CharField(max_length=50, db_index=True, help_text='Type: EQ, FUT, CE, PE, etc.')),
                ('segment', models.CharField(max_length=50, db_index=True, help_text='Market segment')),
                ('exchange', models.CharField(max_length=50, db_index=True, help_text='Exchange: NSE, BSE, etc.')),
                
                # Status and metadata
                ('is_active', models.BooleanField(default=True, db_index=True, help_text='Whether instrument is currently tradeable')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'db_table': 'instruments',
                'ordering': ['trading_symbol'],
                'indexes': [
                    # Composite indexes for common query patterns
                    models.Index(fields=['trading_symbol', 'exchange'], name='idx_instruments_symbol_exchange'),
                    models.Index(fields=['instrument_type', 'segment'], name='idx_instruments_type_segment'),
                    models.Index(fields=['exchange', 'is_active'], name='idx_instruments_exchange_active'),
                    models.Index(fields=['expiry'], name='idx_instruments_expiry'),
                    models.Index(fields=['is_active', 'instrument_type'], name='idx_instruments_active_type'),
                ],
            },
        ),

        # Add additional performance indexes
        migrations.RunSQL(
            """
            -- Individual field indexes
            CREATE INDEX idx_instruments_trading_symbol ON instruments(trading_symbol);
            CREATE INDEX idx_instruments_name ON instruments(name);
            CREATE INDEX idx_instruments_exchange ON instruments(exchange);
            CREATE INDEX idx_instruments_instrument_token ON instruments(instrument_token);
            CREATE INDEX idx_instruments_exchange_token ON instruments(exchange_token);
            CREATE INDEX idx_instruments_instrument_type ON instruments(instrument_type);
            CREATE INDEX idx_instruments_segment ON instruments(segment);
            CREATE INDEX idx_instruments_is_active ON instruments(is_active);
            CREATE INDEX idx_instruments_last_price ON instruments(last_price);
            CREATE INDEX idx_instruments_lot_size ON instruments(lot_size);
            CREATE INDEX idx_instruments_created_at ON instruments(created_at);
            
            -- Composite indexes for advanced queries
            CREATE INDEX idx_instruments_symbol_type_exchange ON instruments(trading_symbol, instrument_type, exchange);
            CREATE INDEX idx_instruments_active_expiry ON instruments(is_active, expiry);
            """,
            reverse_sql="""
            -- Drop individual field indexes
            DROP INDEX IF EXISTS idx_instruments_trading_symbol;
            DROP INDEX IF EXISTS idx_instruments_name;
            DROP INDEX IF EXISTS idx_instruments_exchange;
            DROP INDEX IF EXISTS idx_instruments_instrument_token;
            DROP INDEX IF EXISTS idx_instruments_exchange_token;
            DROP INDEX IF EXISTS idx_instruments_instrument_type;
            DROP INDEX IF EXISTS idx_instruments_segment;
            DROP INDEX IF EXISTS idx_instruments_is_active;
            DROP INDEX IF EXISTS idx_instruments_last_price;
            DROP INDEX IF EXISTS idx_instruments_lot_size;
            DROP INDEX IF EXISTS idx_instruments_created_at;
            
            -- Drop composite indexes
            DROP INDEX IF EXISTS idx_instruments_symbol_type_exchange;
            DROP INDEX IF EXISTS idx_instruments_active_expiry;
            """
        ),
    ] 