# Generated by Django 3.0 on 2023-03-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0003_order_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='startted_at',
            new_name='started_at',
        ),
    ]
