# Generated by Django 3.2 on 2023-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0003_alter_algorithm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
