# Generated by Django 4.0.7 on 2023-02-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0003_rename_stock_id_trade_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='status',
        ),
        migrations.AddField(
            model_name='trade',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.stock', verbose_name='Ordered Stock'),
        ),
    ]
