# Generated by Django 3.2 on 2023-09-29 14:13

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0004_auto_20230929_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slto',
            name='order',
        ),
        migrations.AddField(
            model_name='slto',
            name='existing_price_zone',
            field=django_mysql.models.EnumField(choices=[('RESISTANCE_BREAKOUT', 'resistance_breakout'), ('SUPPORT_BREAKOUT', 'support_breakout'), ('RANGE', 'range')], default='range'),
        ),
        migrations.AddField(
            model_name='slto',
            name='existing_price_zone_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slto',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.instrument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slto',
            name='next_price_zone',
            field=django_mysql.models.EnumField(choices=[('RESISTANCE_BREAKOUT', 'resistance_breakout'), ('SUPPORT_BREAKOUT', 'support_breakout'), ('RANGE', 'range')], default='range'),
        ),
    ]
