# Generated by Django 3.2 - Create User Configurations Table

from django.db import migrations, models
import django.utils.timezone
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0004_create_instruments_table'),
    ]

    operations = [
        # Drop the existing user_configurations table if it exists
        migrations.RunSQL(
            "DROP TABLE IF EXISTS user_configurations;",
            reverse_sql="-- Cannot reverse this operation safely"
        ),

        # Create optimized UserConfiguration table
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                
                # User reference - should reference User.public_id (UUID)
                ('user_id', models.UUIDField(unique=True, db_index=True, help_text='References User.public_id')),
                
                # Risk management settings
                ('risk_appetite', models.FloatField(
                    default=5.0, 
                    validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
                    help_text='Risk appetite percentage (0-100)'
                )),
                ('min_reward_risk_ratio', models.FloatField(
                    default=2.0, 
                    validators=[MinValueValidator(0.1)],
                    help_text='Minimum reward to risk ratio'
                )),
                ('max_reward_risk_ratio', models.FloatField(
                    default=20.0, 
                    validators=[MinValueValidator(0.1)],
                    help_text='Maximum reward to risk ratio'
                )),
                
                # Trading session settings
                ('trades_per_session', models.IntegerField(
                    default=100, 
                    validators=[MinValueValidator(1)],
                    help_text='Maximum trades per session'
                )),
                ('max_daily_trades', models.IntegerField(
                    default=500, 
                    validators=[MinValueValidator(1)],
                    help_text='Maximum trades per day'
                )),
                
                # Position management
                ('max_position_size', models.DecimalField(
                    max_digits=12, 
                    decimal_places=2, 
                    default=100000.00,
                    validators=[MinValueValidator(1.00)],
                    help_text='Maximum position size in currency'
                )),
                ('position_size_percentage', models.FloatField(
                    default=10.0, 
                    validators=[MinValueValidator(0.1), MaxValueValidator(100.0)],
                    help_text='Position size as percentage of capital'
                )),
                
                # Stop loss and take profit settings
                ('default_stop_loss_percentage', models.FloatField(
                    default=2.0, 
                    validators=[MinValueValidator(0.1), MaxValueValidator(50.0)],
                    help_text='Default stop loss percentage'
                )),
                ('default_take_profit_percentage', models.FloatField(
                    default=4.0, 
                    validators=[MinValueValidator(0.1), MaxValueValidator(100.0)],
                    help_text='Default take profit percentage'
                )),
                
                # Status and metadata
                ('is_active', models.BooleanField(default=True, db_index=True, help_text='Whether configuration is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Configuration',
                'verbose_name_plural': 'User Configurations',
                'db_table': 'user_configurations',
                'ordering': ['user_id'],
            },
        ),

        # Add performance indexes and constraints
        migrations.RunSQL(
            """
            -- Indexes for user_configurations
            CREATE INDEX idx_user_config_user_id ON user_configurations(user_id);
            CREATE INDEX idx_user_config_active ON user_configurations(is_active);
            CREATE INDEX idx_user_config_created ON user_configurations(created_at);
            CREATE INDEX idx_user_config_risk ON user_configurations(risk_appetite);
            
            -- Constraints to ensure data integrity
            ALTER TABLE user_configurations 
            ADD CONSTRAINT chk_reward_risk_ratio_order 
            CHECK (min_reward_risk_ratio <= max_reward_risk_ratio);
            
            ALTER TABLE user_configurations 
            ADD CONSTRAINT chk_stop_loss_take_profit_order 
            CHECK (default_stop_loss_percentage <= default_take_profit_percentage);
            """,
            reverse_sql="""
            -- Drop indexes
            DROP INDEX IF EXISTS idx_user_config_user_id;
            DROP INDEX IF EXISTS idx_user_config_active;
            DROP INDEX IF EXISTS idx_user_config_created;
            DROP INDEX IF EXISTS idx_user_config_risk;
            
            -- Drop constraints
            ALTER TABLE user_configurations DROP CONSTRAINT IF EXISTS chk_reward_risk_ratio_order;
            ALTER TABLE user_configurations DROP CONSTRAINT IF EXISTS chk_stop_loss_take_profit_order;
            """
        ),
    ] 