# Generated by Django 4.0.7 on 2023-02-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0004_remove_trade_status_trade_is_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.trade', verbose_name='Trade ID')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
