# Generated by Django 3.0 on 2023-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0004_auto_20230309_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trading_alog_id',
            field=models.IntegerField(default=1),
        ),
    ]
