# Generated by Django 3.0 on 2023-03-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0005_trade_trading_alog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='trade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='net_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
