# Generated by Django 4.0.7 on 2023-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSession',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('net_profit', models.FloatField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'trade_sessions',
            },
        ),
    ]
