# Generated by Django 3.2 - Create Trade Sessions Table

from django.db import migrations, models
import django.utils.timezone
from django_mysql.models import EnumField
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats_gateway', '0001_create_users_table'),
        ('trade_management_unit', '0005_create_user_configurations_table'),
    ]

    operations = [
        # Create TradeSession table
        migrations.CreateModel(
            name='TradeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                
                # User reference - ForeignKey to User.public_id
                ('user_id', models.ForeignKey(
                    'ats_gateway.User',
                    to_field='public_id',
                    on_delete=models.CASCADE,
                    db_column='user_id',
                    help_text='References User.public_id'
                )),
                
                # Session status and timing
                ('status', EnumField(
                    choices=[
                        ('started', 'Started'),
                        ('paused', 'Paused'),
                        ('stopped', 'Stopped'),
                    ],
                    default='started',
                    db_index=True,
                    help_text='Current status of the trading session'
                )),
                ('started_at', models.DateTimeField(
                    blank=False,
                    help_text='When the trading session was started'
                )),
                ('closed_at', models.DateTimeField(
                    blank=True,
                    null=True,
                    help_text='When the trading session was closed'
                )),
                
                # Session configuration
                ('dummy', models.BooleanField(
                    default=False,
                    help_text='Whether this is a paper trading session'
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    db_index=True,
                    help_text='Whether the session is currently active'
                )),
                
                # Algorithm references
                ('initiation_algorithm', models.ForeignKey(
                    'trade_management_unit.InitiationAlgorithm',
                    on_delete=models.CASCADE,
                    help_text='Algorithm used for trade initiation'
                )),
                ('termination_algorithm', models.ForeignKey(
                    'trade_management_unit.TerminationAlgorithm',
                    on_delete=models.CASCADE,
                    help_text='Algorithm used for trade termination'
                )),
                ('scanning_algorithm', models.ForeignKey(
                    'trade_management_unit.ScanningAlgorithm',
                    on_delete=models.CASCADE,
                    help_text='Algorithm used for market scanning'
                )),
                
                # Trading frequency
                ('trading_frequency', EnumField(
                    choices=[
                        ('5minute', '5minute'),
                        ('10minute', '10minute'),
                        ('15minute', '15minute'),
                        ('30minute', '30minute'),
                        ('1hour', '1hour'),
                        ('4hour', '4hour'),
                        ('1day', '1day'),
                    ],
                    default='10minute',
                    db_index=True,
                    help_text='Frequency for trading decisions'
                )),
            ],
            options={
                'verbose_name': 'Trade Session',
                'verbose_name_plural': 'Trade Sessions',
                'db_table': 'trade_sessions',
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(fields=['user_id'], name='idx_trade_sessions_user'),
                    models.Index(fields=['scanning_algorithm'], name='idx_trade_sess_scan_algo'),
                    models.Index(fields=['initiation_algorithm'], name='idx_trade_sess_init_algo'),
                    models.Index(fields=['termination_algorithm'], name='idx_trade_sess_term_algo'),
                    models.Index(fields=['trading_frequency'], name='idx_trade_sess_frequency'),
                ],
            },
        ),

        # Add performance indexes for trade_sessions table
        migrations.RunSQL(
            """
            -- Primary indexes for trade_sessions
            CREATE INDEX idx_trade_sess_status ON trade_sessions(status);
            CREATE INDEX idx_trade_sess_started ON trade_sessions(started_at);
            CREATE INDEX idx_trade_sess_closed ON trade_sessions(closed_at);
            CREATE INDEX idx_trade_sess_dummy ON trade_sessions(dummy);
            CREATE INDEX idx_trade_sess_active ON trade_sessions(is_active);
            
            -- Composite indexes for common query patterns
            CREATE INDEX idx_trade_sess_user_status ON trade_sessions(user_id, status);
            CREATE INDEX idx_trade_sess_user_active ON trade_sessions(user_id, is_active);
            CREATE INDEX idx_trade_sess_active_start ON trade_sessions(is_active, started_at);
            CREATE INDEX idx_trade_sess_user_dummy ON trade_sessions(user_id, dummy);
            CREATE INDEX idx_trade_sess_status_freq ON trade_sessions(status, trading_frequency);
            """,
            reverse_sql="""
            -- Drop primary indexes
            DROP INDEX IF EXISTS idx_trade_sess_status;
            DROP INDEX IF EXISTS idx_trade_sess_started;
            DROP INDEX IF EXISTS idx_trade_sess_closed;
            DROP INDEX IF EXISTS idx_trade_sess_dummy;
            DROP INDEX IF EXISTS idx_trade_sess_active;
            
            -- Drop composite indexes
            DROP INDEX IF EXISTS idx_trade_sess_user_status;
            DROP INDEX IF EXISTS idx_trade_sess_user_active;
            DROP INDEX IF EXISTS idx_trade_sess_active_start;
            DROP INDEX IF EXISTS idx_trade_sess_user_dummy;
            DROP INDEX IF EXISTS idx_trade_sess_status_freq;
            """
        ),

        # Add business logic constraints
        migrations.RunSQL(
            """
            -- Ensure session dates are logical
            ALTER TABLE trade_sessions 
            ADD CONSTRAINT chk_trade_sess_date_order 
            CHECK (closed_at IS NULL OR closed_at >= started_at);
            """,
            reverse_sql="""
            ALTER TABLE trade_sessions DROP CONSTRAINT IF EXISTS chk_trade_sess_date_order;
            """
        ),
    ] 