# Generated by Django 3.2 on 2023-09-29 14:20

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0005_auto_20230929_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesession',
            name='trading_frequency',
            field=django_mysql.models.EnumField(choices=[('minute', 'minute'), ('3minute', '3minute'), ('5minute', '5minute'), ('10minute', '10minute'), ('15minute', '15minute'), ('30minute', '30minute'), ('60minute', '60minute'), ('day', 'day')], default='10minute'),
        ),
    ]
