# Generated by Django 3.2 - Create Trades Table

from django.db import migrations, models
import django.utils.timezone
from django_mysql.models import EnumField
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0006_create_trade_sessions_table'),
    ]

    operations = [
        # Create Trade table
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                
                # Trade status and timing
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('started_at', models.DateTimeField(
                    blank=False,
                    help_text='When the trade was initiated'
                )),
                ('closed_at', models.DateTimeField(
                    blank=True,
                    null=True,
                    help_text='When the trade was closed'
                )),
                
                # Trade relationships
                ('instrument', models.ForeignKey(
                    'trade_management_unit.Instrument',
                    verbose_name='Ordered Instrument',
                    on_delete=models.CASCADE,
                    help_text='The financial instrument for this trade'
                )),
                ('trade_session', models.ForeignKey(
                    'trade_management_unit.TradeSession',
                    verbose_name='Trade Session',
                    on_delete=models.CASCADE,
                    default=None,
                    help_text='The trading session this trade belongs to'
                )),
                
                # Trade details
                ('net_profit', models.DecimalField(
                    max_digits=9,
                    decimal_places=2,
                    blank=True,
                    null=True,
                    help_text='Net profit/loss from this trade'
                )),
                ('view', EnumField(
                    choices=[('long', 'long'), ('short', 'short')],
                    default='long',
                    help_text='Trade direction: long or short'
                )),
                ('user_id', models.CharField(
                    max_length=64,
                    default='1',
                    db_index=True,
                    help_text='User identifier'
                )),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['-started_at'],
            },
        ),

        # Add performance indexes for trades table
        migrations.RunSQL(
            """
            -- Primary indexes for trades
            CREATE INDEX idx_trades_is_active ON trades(is_active);
            CREATE INDEX idx_trades_started_at ON trades(started_at);
            CREATE INDEX idx_trades_closed_at ON trades(closed_at);
            CREATE INDEX idx_trades_user_id ON trades(user_id);
            CREATE INDEX idx_trades_view ON trades(view);
            
            -- Relationship indexes
            CREATE INDEX idx_trades_instrument ON trades(instrument_id);
            CREATE INDEX idx_trades_trade_session ON trades(trade_session_id);
            
            -- Composite indexes for common query patterns
            CREATE INDEX idx_trades_user_active ON trades(user_id, is_active);
            CREATE INDEX idx_trades_session_active ON trades(trade_session_id, is_active);
            CREATE INDEX idx_trades_instrument_active ON trades(instrument_id, is_active);
            CREATE INDEX idx_trades_active_started ON trades(is_active, started_at);
            """,
            reverse_sql="""
            -- Drop primary indexes
            DROP INDEX IF EXISTS idx_trades_is_active;
            DROP INDEX IF EXISTS idx_trades_started_at;
            DROP INDEX IF EXISTS idx_trades_closed_at;
            DROP INDEX IF EXISTS idx_trades_user_id;
            DROP INDEX IF EXISTS idx_trades_view;
            
            -- Drop relationship indexes
            DROP INDEX IF EXISTS idx_trades_instrument;
            DROP INDEX IF EXISTS idx_trades_trade_session;
            
            -- Drop composite indexes
            DROP INDEX IF EXISTS idx_trades_user_active;
            DROP INDEX IF EXISTS idx_trades_session_active;
            DROP INDEX IF EXISTS idx_trades_instrument_active;
            DROP INDEX IF EXISTS idx_trades_active_started;
            """
        ),

        # Add business logic constraints
        migrations.RunSQL(
            """
            -- Ensure trade dates are logical
            ALTER TABLE trades 
            ADD CONSTRAINT chk_trades_date_order 
            CHECK (closed_at IS NULL OR closed_at >= started_at);
            """,
            reverse_sql="""
            ALTER TABLE trades DROP CONSTRAINT IF EXISTS chk_trades_date_order;
            """
        ),
    ] 