# Generated by Django 3.2 on 2023-10-21 10:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0006_tradesession_trading_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=200)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_balance_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dummy_users',
            },
        ),
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('risk_appetite', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_reward_ratio', models.FloatField(default=0.5)),
            ],
            options={
                'db_table': 'user_configurations',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['user_id'], name='trade_sessi_user_id_bed6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['scanning_algorithm'], name='trade_sessi_scannin_e2fdfb_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['tracking_algorithm'], name='trade_sessi_trackin_99b0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['trading_frequency'], name='trade_sessi_trading_ef3d16_idx'),
        ),
    ]
