# Generated by Django 4.0.7 on 2023-02-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0006_tradesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.tradesession', verbose_name='Trade Session'),
        ),
    ]
