# Generated by Django 3.2 on 2023-10-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0007_auto_20231021_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algoudtsscanrecord',
            old_name='resistence_price',
            new_name='resistance_price',
        ),
        migrations.RenameField(
            model_name='algoudtsscanrecord',
            old_name='resistence_strength',
            new_name='resistance_strength',
        ),
    ]
