# Generated by Django 3.2 - Create Orders Table

from django.db import migrations, models
import django.utils.timezone
from django_mysql.models import EnumField
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('ats_gateway', '0001_create_users_table'),
        ('trade_management_unit', '0007_create_trades_table'),
    ]

    operations = [
        # Drop existing orders table if it exists to start fresh
        migrations.RunSQL(
            "DROP TABLE IF EXISTS orders;",
            reverse_sql="-- Cannot reverse this operation safely"
        ),

        # Create optimized Order table
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                
                # User reference - ForeignKey to User.public_id
                ('user_id', models.ForeignKey(
                    'ats_gateway.User',
                    to_field='public_id',
                    on_delete=models.CASCADE,
                    db_column='user_id',
                    help_text='References User.public_id'
                )),
                
                # Order status and type
                ('status', EnumField(
                    choices=[
                        ('pending', 'Pending'),
                        ('executed', 'Executed'),
                        ('rejected', 'Rejected'),
                        ('cancelled', 'Cancelled'),
                        ('partially_filled', 'Partially Filled')
                    ],
                    default='pending',
                    db_index=True,
                    help_text='Current status of the order'
                )),
                ('order_type', EnumField(
                    choices=[('buy', 'Buy'), ('sell', 'Sell')],
                    db_index=True,
                    help_text='Order type: buy or sell'
                )),
                
                # Order timing
                ('started_at', models.DateTimeField(
                    default=django.utils.timezone.now,
                    help_text='When the order was placed'
                )),
                ('closed_at', models.DateTimeField(
                    blank=True,
                    null=True,
                    help_text='When the order was executed/closed'
                )),
                
                # Order relationships
                ('instrument', models.ForeignKey(
                    'trade_management_unit.Instrument',
                    on_delete=models.PROTECT,
                    verbose_name='instrument_id',
                    help_text='The financial instrument for this order'
                )),
                ('trade', models.ForeignKey(
                    'trade_management_unit.Trade',
                    on_delete=models.CASCADE,
                    verbose_name='trade_id',
                    help_text='The parent trade for this order'
                )),
                ('trade_session', models.ForeignKey(
                    'trade_management_unit.TradeSession',
                    on_delete=models.CASCADE,
                    verbose_name='trade_session_id',
                    help_text='The trading session this order belongs to'
                )),
                
                # Order details
                ('quantity', models.IntegerField(
                    default=1,
                    help_text='Number of units in this order'
                )),
                ('price', models.DecimalField(
                    max_digits=12,
                    decimal_places=2,
                    blank=True,
                    null=True,
                    help_text='Order price per unit'
                )),
                ('filled_quantity', models.IntegerField(
                    default=0,
                    help_text='Number of units that have been filled'
                )),
                ('average_price', models.DecimalField(
                    max_digits=12,
                    decimal_places=2,
                    blank=True,
                    null=True,
                    help_text='Average execution price'
                )),
                
                # Broker integration
                ('broker_order_id', models.CharField(
                    max_length=64,
                    blank=True,
                    null=True,
                    db_index=True,
                    help_text='Generic broker order ID'
                )),
                
                # Order execution details
                ('frictional_losses', models.DecimalField(
                    max_digits=10,
                    decimal_places=2,
                    blank=True,
                    null=True,
                    default=Decimal('0.00'),
                    help_text='Fees, taxes, and other charges'
                )),
                ('total_value', models.DecimalField(
                    max_digits=15,
                    decimal_places=2,
                    default=Decimal('0.00'),
                    help_text='Total value of the order'
                )),
                
                # Order metadata
                ('order_notes', models.TextField(
                    blank=True,
                    null=True,
                    help_text='Notes or comments about this order'
                )),
                ('rejection_reason', models.CharField(
                    max_length=200,
                    blank=True,
                    null=True,
                    help_text='Reason for order rejection'
                )),
                ('order_source', models.CharField(
                    max_length=50,
                    default='system',
                    help_text='Source of the order: system, manual, etc.'
                )),
                
                # Timestamps
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),

        # Add performance indexes and constraints
        migrations.RunSQL(
            """
            -- Primary indexes for orders
            CREATE INDEX idx_orders_user_id ON orders(user_id);
            CREATE INDEX idx_orders_status ON orders(status);
            CREATE INDEX idx_orders_order_type ON orders(order_type);
            CREATE INDEX idx_orders_started_at ON orders(started_at);
            CREATE INDEX idx_orders_closed_at ON orders(closed_at);
            CREATE INDEX idx_orders_broker_order_id ON orders(broker_order_id);
            CREATE INDEX idx_orders_created_at ON orders(created_at);
            
            -- Relationship indexes
            CREATE INDEX idx_orders_instrument ON orders(instrument_id);
            CREATE INDEX idx_orders_trade ON orders(trade_id);
            CREATE INDEX idx_orders_trade_session ON orders(trade_session_id);
            
            -- Composite indexes for common query patterns
            CREATE INDEX idx_orders_user_status ON orders(user_id, status);
            CREATE INDEX idx_orders_user_trade ON orders(user_id, trade_id);
            CREATE INDEX idx_orders_trade_type ON orders(trade_id, order_type);
            CREATE INDEX idx_orders_session_status ON orders(trade_session_id, status);
            CREATE INDEX idx_orders_instrument_type ON orders(instrument_id, order_type);
            CREATE INDEX idx_orders_status_date ON orders(status, started_at);
            CREATE INDEX idx_orders_user_session ON orders(user_id, trade_session_id);
            CREATE INDEX idx_orders_execution_tracking ON orders(status, broker_order_id, started_at);
            """,
            reverse_sql="""
            -- Drop primary indexes
            DROP INDEX IF EXISTS idx_orders_user_id;
            DROP INDEX IF EXISTS idx_orders_status;
            DROP INDEX IF EXISTS idx_orders_order_type;
            DROP INDEX IF EXISTS idx_orders_started_at;
            DROP INDEX IF EXISTS idx_orders_closed_at;
            DROP INDEX IF EXISTS idx_orders_broker_order_id;
            DROP INDEX IF EXISTS idx_orders_created_at;
            
            -- Drop relationship indexes
            DROP INDEX IF EXISTS idx_orders_instrument;
            DROP INDEX IF EXISTS idx_orders_trade;
            DROP INDEX IF EXISTS idx_orders_trade_session;
            
            -- Drop composite indexes
            DROP INDEX IF EXISTS idx_orders_user_status;
            DROP INDEX IF EXISTS idx_orders_user_trade;
            DROP INDEX IF EXISTS idx_orders_trade_type;
            DROP INDEX IF EXISTS idx_orders_session_status;
            DROP INDEX IF EXISTS idx_orders_instrument_type;
            DROP INDEX IF EXISTS idx_orders_status_date;
            DROP INDEX IF EXISTS idx_orders_user_session;
            DROP INDEX IF EXISTS idx_orders_execution_tracking;
            """
        ),

        # Add business logic constraints
        migrations.RunSQL(
            """
            -- Ensure order dates are logical
            ALTER TABLE orders 
            ADD CONSTRAINT chk_orders_date_order 
            CHECK (closed_at IS NULL OR closed_at >= started_at);
            
            -- Ensure positive values
            ALTER TABLE orders 
            ADD CONSTRAINT chk_orders_positive_quantity 
            CHECK (quantity > 0 AND filled_quantity >= 0 AND filled_quantity <= quantity);
            
            -- Ensure positive amounts
            ALTER TABLE orders 
            ADD CONSTRAINT chk_orders_positive_amounts 
            CHECK (
                (frictional_losses IS NULL OR frictional_losses >= 0) AND
                total_value >= 0
            );
            
            -- Ensure prices are positive when set
            ALTER TABLE orders 
            ADD CONSTRAINT chk_orders_positive_prices 
            CHECK (
                (price IS NULL OR price > 0) AND
                (average_price IS NULL OR average_price > 0)
            );
            """,
            reverse_sql="""
            ALTER TABLE orders DROP CONSTRAINT IF EXISTS chk_orders_date_order;
            ALTER TABLE orders DROP CONSTRAINT IF EXISTS chk_orders_positive_quantity;
            ALTER TABLE orders DROP CONSTRAINT IF EXISTS chk_orders_positive_amounts;
            ALTER TABLE orders DROP CONSTRAINT IF EXISTS chk_orders_positive_prices;
            """
        ),

        # Add unique constraint for trade and order_type combination
        migrations.RunSQL(
            """
            ALTER TABLE orders 
            ADD CONSTRAINT unique_trade_order_type 
            UNIQUE (trade_id, order_type);
            """,
            reverse_sql="""
            ALTER TABLE orders DROP CONSTRAINT IF EXISTS unique_trade_order_type;
            """
        ),
    ] 