# Generated by Django 3.2 on 2023-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0007_auto_20230309_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trading_alog_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
