# Generated by Django 3.2 on 2023-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0008_auto_20230503_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='scanning_alogo_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
