# Generated by Django 3.2 - Create Seed Tracker Table

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0008_create_orders_table'),
    ]

    operations = [
        # Create SeedTracker table to track applied seed files
        migrations.CreateModel(
            name='SeedTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seed_name', models.CharField(
                    max_length=255, 
                    unique=True, 
                    help_text='Name of the seed file that was applied'
                )),
                ('applied_at', models.DateTimeField(
                    default=django.utils.timezone.now,
                    help_text='When the seed was applied'
                )),
            ],
            options={
                'verbose_name': 'Seed Tracker',
                'verbose_name_plural': 'Seed Trackers',
                'db_table': 'seed_tracker',
                'ordering': ['-applied_at'],
            },
        ),

        # Add indexes for performance
        migrations.RunSQL(
            """
            CREATE INDEX idx_seed_tracker_name ON seed_tracker(seed_name);
            CREATE INDEX idx_seed_tracker_applied ON seed_tracker(applied_at);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_seed_tracker_name;
            DROP INDEX IF EXISTS idx_seed_tracker_applied;
            """
        ),
    ] 