# Generated by Django 3.2 on 2023-10-23 06:08

from django.db import migrations, models
import trade_management_unit.Constants.TmuConstants


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0008_auto_20231022_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoudtsscanrecord',
            name='effective_trend',
            field=models.CharField(choices=[('uptrend', 'uptrend'), ('downtrend', 'downtrend'), ('sidetrend', 'sidetrend')], default=trade_management_unit.Constants.TmuConstants.Trends['UPTREND'], max_length=20),
        ),
    ]
