# Generated by Django 3.2 on 2023-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0009_auto_20231026_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DummyUser',
            new_name='DummyAccount',
        ),
        migrations.AlterModelTable(
            name='dummyaccount',
            table='dummy_accounts',
        ),
    ] 