# Generated by Django 3.2 on 2023-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0009_auto_20230503_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.BigIntegerField()),
                ('exchange_token', models.BigIntegerField()),
                ('trading_symbol', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry', models.DateField(null=True)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tick_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=50)),
                ('exchange', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'instruments',
            },
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['trading_symbol'], name='instruments_trading_107c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['name'], name='instruments_name_9d146b_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['exchange'], name='instruments_exchang_ea4098_idx'),
        ),
    ]
