# Generated by Django 3.2 on 2023-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0009_alter_algoudtsscanrecord_effective_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
