# Generated by trade_management_unit scanner events migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0009_create_seed_tracker_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(default='eligible_instrument_found', max_length=50)),
                ('trade_session_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('trading_symbol', models.CharField(db_index=True, max_length=200)),
                ('support_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resistance_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_action', models.CharField(blank=True, max_length=10, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.instrument')),
                ('scanning_algorithm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.scanningalgorithm', to_field='name')),
                ('initiation_algorithm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.initiationalgorithm', to_field='name')),
                ('termination_algorithm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.terminationalgorithm', to_field='name')),
            ],
            options={
                'db_table': 'scanner_events',
            },
        ),
        migrations.AddIndex(
            model_name='scannerevent',
            index=models.Index(fields=['trade_session_id'], name='scanner_eve_trade_s_df8c52_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerevent',
            index=models.Index(fields=['event_type'], name='scanner_eve_event_t_9d04ac_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerevent',
            index=models.Index(fields=['timestamp'], name='scanner_eve_timesta_28e736_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerevent',
            index=models.Index(fields=['scanning_algorithm_name'], name='scanner_eve_scannin_3e5b72_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerevent',
            index=models.Index(fields=['instrument'], name='scanner_eve_instrum_b8fa91_idx'),
        ),
    ] 