# Generated by Django 3.2 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0010_auto_20231027_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoudtsscanrecord',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ] 