# Generated by Django 3.2 on 2023-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0011_auto_20231026_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.BigAutoField(auto_created=True, max_length=64, primary_key=True, serialize=False),
        ),
    ]
