# Generated by Django 3.2 on 2023-11-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0011_auto_20231107_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='frictional_losses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ] 