# Generated by Django 3.2 on 2023-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0012_alter_trade_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DummyUser',
            new_name='DummyAccount',
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dummyaccount',
            table='dummy_accounts',
        ),
    ]
