# Generated by Django 3.2 on 2023-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0013_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoudtsscanrecord',
            name='effective_trend',
            field=models.CharField(choices=[('uptrend', 'uptrend'), ('downtrend', 'downtrend'), ('sidetrend', 'sidetrend')], default='uptrend', max_length=20),
        ),
        migrations.AlterField(
            model_name='algosltotrackrecord',
            name='existing_price_zone',
            field=models.CharField(choices=[('RESISTANCE_BREAKOUT', 'resistance_breakout'), ('SUPPORT_BREAKOUT', 'support_breakout'), ('RANGE', 'range')], default='range', max_length=50),
        ),
        migrations.AlterField(
            model_name='algosltotrackrecord',
            name='next_price_zone',
            field=models.CharField(choices=[('RESISTANCE_BREAKOUT', 'resistance_breakout'), ('SUPPORT_BREAKOUT', 'support_breakout'), ('RANGE', 'range')], default='range', max_length=50),
        ),
    ] 