# Generated by Django 3.2 on 2023-10-27 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0014_auto_20231027_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyaccount',
            name='last_balance_refreshed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
    ]
