# Generated by Django 3.2 on 2023-10-27 15:47

from django.db import migrations, models
from trade_management_unit.lib.common.Utils.Utils import *

class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0015_alter_dummyaccount_last_balance_refreshed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=current_ist, null=True),
        ),
    ]
