# Generated by Django 3.2 on 2023-11-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0015_order_trade_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('trade', 'order_type')},
        ),
    ] 