# Generated by Django 3.2 on 2023-10-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0016_alter_order_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoudtsscanrecord',
            name='instrument_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.instrument'),
            preserve_default=False,
        ),
    ]
