# Generated by Django 3.2 on 2023-10-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0018_auto_20231028_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoudtsscanrecord',
            name='tracking_algo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algoudtsscanrecord',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
