# Generated by Django 3.2 on 2023-10-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0019_auto_20231028_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slto',
            new_name='AlgoSltoTrackRecord',
        ),
    ]
