# Generated by Django 3.2 on 2023-10-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0020_rename_slto_algosltotrackrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
