# Generated by Django 3.2 on 2023-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0022_auto_20231030_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyaccount',
            name='last_balance_refreshed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
