# Generated by Django 3.2 on 2023-11-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0023_alter_dummyaccount_last_balance_refreshed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algoudtsscanrecord',
            old_name='instrument_id',
            new_name='instrument',
        ),
    ]
