# Generated by Django 3.2 on 2023-11-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0024_rename_instrument_id_algoudtsscanrecord_instrument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='algoudtsscanrecord',
            unique_together={('trade', 'instrument')},
        ),
    ]
