# Generated by Django 3.2 on 2023-11-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0027_alter_algosltotrackrecord_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algosltotrackrecord',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade_management_unit.instrument'),
        ),
    ]
