# Generated by Django 3.2 on 2023-11-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0028_alter_algosltotrackrecord_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algosltotrackrecord',
            name='trade_session',
        ),
        migrations.AddField(
            model_name='algosltotrackrecord',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.trade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algoudtsscanrecord',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade_management_unit.instrument'),
        ),
    ]
