# Generated by Django 3.2 on 2023-11-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0029_auto_20231105_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algoudtsscanrecord',
            name='tracking_algo_id',
        ),
        migrations.AddField(
            model_name='algosltotrackrecord',
            name='scanning_algo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trade_management_unit.algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algoudtsscanrecord',
            name='tracking_algo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trade_management_unit.algorithm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='algosltotrackrecord',
            unique_together={('trade', 'instrument')},
        ),
    ]
