# Generated by Django 3.2 on 2023-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0030_auto_20231105_1121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='algosltotrackrecord',
            unique_together=set(),
        ),
    ]
