# Generated by Django 3.2 on 2023-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0031_alter_algosltotrackrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='margin',
            field=models.FloatField(default=0),
        ),
    ]
