# Generated by Django 3.2 on 2023-11-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0032_trade_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfiguration',
            old_name='reward_risk_ratio',
            new_name='min_reward_risk_ratio',
        ),
        migrations.AddField(
            model_name='userconfiguration',
            name='max_reward_risk_ratio',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='userconfiguration',
            name='trades_per_session',
            field=models.IntegerField(default=100),
        ),
    ]
