# Generated by Django 3.2 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0033_auto_20231106_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoudtsscanrecord',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
