# Generated by Django 3.2 on 2023-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0036_auto_20231108_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='display_name',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
