# Generated by Django 3.2 on 2023-12-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0038_order_trade_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('trade', 'order_type')},
        ),
    ]
