# Generated by Django 3.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0039_alter_order_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanningAlgorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, db_index=True)),
                ('display_name', models.CharField(max_length=255, db_index=True, default=None)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'scanning_algorithms',
                'verbose_name': 'scanning algorithm',
                'verbose_name_plural': 'scanning algorithms',
            },
        ),
        migrations.CreateModel(
            name='InitiationAlgorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, db_index=True)),
                ('display_name', models.CharField(max_length=255, db_index=True, default=None)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'initiation_algorithms',
                'verbose_name': 'initiation algorithm',
                'verbose_name_plural': 'initiation algorithms',
            },
        ),
        migrations.CreateModel(
            name='TerminationAlgorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, db_index=True)),
                ('display_name', models.CharField(max_length=255, db_index=True, default=None)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'termination_algorithms',
                'verbose_name': 'termination algorithm',
                'verbose_name_plural': 'termination algorithms',
            },
        ),
    ] 