# Generated by Django 3.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management_unit', '0040_create_algorithm_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesession',
            name='scanning_algorithm',
        ),
        migrations.RemoveField(
            model_name='tradesession',
            name='tracking_algorithm',
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tradesession',
            name='scanning_algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.scanningalgorithm', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradesession',
            name='initiation_algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.initiationalgorithm', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradesession',
            name='termination_algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_management_unit.terminationalgorithm', default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['scanning_algorithm'], name='trade_sessi_scannin_f3e42a_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['initiation_algorithm'], name='trade_sessi_initiat_8a2f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesession',
            index=models.Index(fields=['termination_algorithm'], name='trade_sessi_termina_6b3d4e_idx'),
        ),
    ] 