# Generated by Django 3.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats_gateway', '0001_initial'),  # For the User model
        ('trade_management_unit', '0041_update_tradesession_algorithm_fields'),
    ]

    operations = [
        # First, remove the foreign key fields that reference the Algorithm model
        migrations.RemoveField(
            model_name='algosltotrackrecord',
            name='scanning_algo',
        ),
        
        migrations.RemoveField(
            model_name='algoudtsscanrecord',
            name='tracking_algo',
        ),
        
        # Safely drop the algorithms table if it exists (using raw SQL)
        migrations.RunSQL(
            "DROP TABLE IF EXISTS algorithms;",
            reverse_sql="-- Cannot reverse this operation safely"
        ),
        
        # Fix the TradeSession user_id foreign key relationship
        # First, drop the index on user_id to allow column modification
        migrations.RunSQL(
            "DROP INDEX trade_sessi_user_id_bed6cb_idx ON trade_sessions;",
            reverse_sql="CREATE INDEX trade_sessi_user_id_bed6cb_idx ON trade_sessions (user_id);"
        ),
        
        # Modify the user_id column to match the users.public_id field type
        migrations.RunSQL(
            "ALTER TABLE trade_sessions MODIFY COLUMN user_id char(32) NOT NULL;",
            reverse_sql="ALTER TABLE trade_sessions MODIFY COLUMN user_id varchar(64) NOT NULL;"
        ),
        
        # Add the foreign key constraint
        migrations.RunSQL(
            "ALTER TABLE trade_sessions ADD CONSTRAINT trade_sessions_user_id_fk_users_public_id FOREIGN KEY (user_id) REFERENCES users (public_id);",
            reverse_sql="ALTER TABLE trade_sessions DROP FOREIGN KEY trade_sessions_user_id_fk_users_public_id;"
        ),
        
        # Recreate the index on user_id
        migrations.RunSQL(
            "CREATE INDEX trade_sessi_user_id_bed6cb_idx ON trade_sessions (user_id);",
            reverse_sql="DROP INDEX trade_sessi_user_id_bed6cb_idx ON trade_sessions;"
        ),
    ] 