"""
Base Scanner Interface for the scanning service.
Defines the standardized event format that all scanner algorithms must follow.
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List

# Import dependencies that were previously scattered in methods
from scanning_service.lib.utils.redis import get_scanning_event_publisher
from scanning_service.lib.data_providers import TMUServiceProvider
from scanning_service.lib.utils.logger import log


class BaseScannerInterface(ABC):
    """
    Abstract base class for all scanner algorithms.
    Ensures consistent event format across different scanning algorithms.
    """
    
    # Standardized field names for eligible instrument events (complete event format)
    STANDARD_EVENT_FIELDS = [
        'event_id',           # Required: Unique event identifier (generated by publisher)
        'event_type',         # Required: Type of event (e.g., "eligible_instrument_found")
        'trade_session_id',   # Required: Trade session ID for event correlation
        'timestamp',          # Required: Event timestamp in ISO format
        'instrument_id',      # Required: Unique identifier for the instrument
        'trading_symbol',     # Required: Trading symbol (e.g., "RELIANCE")
        'support_price',      # Optional: Support price level (None if not applicable)
        'resistance_price',   # Optional: Resistance price level (None if not applicable)
        'required_action',    # Optional: "buy", "sell", or None
        'market_price',       # Required: Current market price
        'scanner_type'        # Required: Type of scanner that found the instrument
    ]
    
    # Instrument-specific fields (subset of STANDARD_EVENT_FIELDS for scanner output)
    INSTRUMENT_DATA_FIELDS = [
        'instrument_id',      # Required: Unique identifier for the instrument
        'trading_symbol',     # Required: Trading symbol (e.g., "RELIANCE") 
        'support_price',      # Optional: Support price level (None if not applicable)
        'resistance_price',   # Optional: Resistance price level (None if not applicable)
        'required_action',    # Optional: "buy", "sell", or None
        'market_price'        # Required: Current market price
    ]
    
    def __init__(self):
        """
        Initialize the scanner with minimal setup.
        Use configure() method to set up the scanner with required parameters.
        """
        self.trade_frequency = None
        self.event_publisher = None
        self._configured = False
    
    @abstractmethod
    def configure(self, trade_freq: str, **kwargs):
        """
        Configure the scanner with required parameters and dependencies.
        Each scanner implementation can accept different configuration parameters.
        
        Note: user_id and trade_session_id are passed as parameters but not stored
        as instance state since scanners are now frequency-based singletons.
        
        Args:
            trade_freq: Trading frequency (e.g., "5minute")
            **kwargs: Additional scanner-specific configuration parameters
                     May include user_id, trade_session_id for method calls
        """
        self.trade_frequency = trade_freq
        
        # Initialize event publisher (common across all scanners)
        if not self.event_publisher:
            self.event_publisher = get_scanning_event_publisher()
        
        # Initialize TMU service provider for fetching active trade sessions
        if not hasattr(self, 'tmu_provider') or not self.tmu_provider:
            self.tmu_provider = TMUServiceProvider()
        
        self._configured = True
    
    def is_configured(self) -> bool:
        """
        Check if the scanner has been properly configured.
        
        Returns:
            bool: True if configured, False otherwise
        """
        return self._configured
    
    def _ensure_configured(self):
        """
        Ensure the scanner is configured before running operations.
        
        Raises:
            RuntimeError: If scanner is not configured
        """
        if not self.is_configured():
            raise RuntimeError(f"Scanner {self.__class__.__name__} must be configured before use. Call configure() first.")
    
    @abstractmethod
    def is_eligible(self, symbol: str) -> tuple[bool, Dict[str, Any]]:
        """
        Check if an instrument is eligible for trading based on the scanner's criteria.
        
        Args:
            symbol: Trading symbol to check
            
        Returns:
            tuple: (is_eligible: bool, eligibility_data: dict)
        """
        pass
    
    @abstractmethod
    def fetch_instrument_tokens_and_start_tracking(self, user_id: str, dummy: bool):
        """
        Start the scanner to fetch instruments and begin tracking.
        
        Args:
            user_id: User ID
            dummy: Whether this is a dummy/paper trading session
        """
        pass
    
    @abstractmethod
    def stop_scanning(self):
        """
        Stop the scanner gracefully.
        """
        pass
    
    def format_eligible_instrument(self, instrument_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Format instrument data according to the standardized instrument data format.
        All scanners must use this method to ensure consistent data structure before publishing.
        
        Args:
            instrument_data: Raw instrument data from the scanner
            
        Returns:
            dict: Standardized instrument data with required fields (matches INSTRUMENT_DATA_FIELDS)
            
        Required fields in input:
            - instrument_id: str or int
            - trading_symbol: str
            - market_price: float
            
        Optional fields (set to None if not available):
            - support_price: float or None
            - resistance_price: float or None
            - required_action: str ("buy", "sell") or None
            
        Note: This returns only instrument-specific data. The event publisher will add
              event metadata (event_id, timestamp, trade_session_id, etc.) to create
              the complete event format defined in STANDARD_EVENT_FIELDS.
        """
        # Validate required fields
        required_fields = ['instrument_id', 'trading_symbol', 'market_price']
        for field in required_fields:
            if field not in instrument_data:
                raise ValueError(f"Missing required field '{field}' in instrument data")
        
        # Create standardized format using INSTRUMENT_DATA_FIELDS
        standardized_data = {}
        for field in self.INSTRUMENT_DATA_FIELDS:
            if field in ['instrument_id', 'trading_symbol', 'market_price']:
                # Required fields
                standardized_data[field] = instrument_data[field]
            else:
                # Optional fields
                standardized_data[field] = instrument_data.get(field)
        
        # Ensure proper data types
        standardized_data['instrument_id'] = str(standardized_data['instrument_id'])
        standardized_data['trading_symbol'] = str(standardized_data['trading_symbol'])
        standardized_data['market_price'] = float(standardized_data['market_price'])
        
        # Ensure price fields are float or None
        for field in ['support_price', 'resistance_price']:
            if standardized_data[field] is not None:
                standardized_data[field] = float(standardized_data[field])
        
        return standardized_data
    
    def publish_eligible_instruments(self, eligible_instruments: List[Dict[str, Any]], scanner_type: str = None) -> None:
        """
        Publish eligible instruments to Redis stream for ALL active trade sessions using this scanner.
        
        This method queries for all active trade sessions that use this scanner algorithm and frequency,
        then publishes one event per session per instrument.
        
        Args:
            eligible_instruments: List of eligible instrument dictionaries in standardized format
            scanner_type: Type of scanner (auto-detected from class name if not provided)
        """
        self._ensure_configured()
        
        if not self.event_publisher:
            log("Event publisher not available, cannot publish eligible instruments", level="error")
            return
        
        # Auto-detect scanner type from class name if not provided
        if scanner_type is None:
            scanner_type = self.__class__.__name__.lower().replace('scanner', '')
        
        # Map scanner type to algorithm ID
        algorithm_id_map = {
            'udts': 1,
            # Add more mappings as algorithms are implemented
            # 'rsi_divergence': 2,
            # 'breakout_scanner': 3,
            # 'momentum_surge': 4
        }
        
        scanning_algo_id = algorithm_id_map.get(scanner_type, 1)  # Default to UDTS (ID 1)
        
        # Fetch active trade sessions for this scanner algorithm ID and frequency
        try:
            active_sessions = self.tmu_provider.fetch_active_trade_sessions(
                scanning_algo_id=scanning_algo_id,
                trading_frequency=self.trade_frequency
            )
            
            if not active_sessions:
                log(f"No active trade sessions found for scanner ID {scanning_algo_id} with frequency {self.trade_frequency}")
                return
            
            log(f"Publishing eligible instruments to {len(active_sessions)} active trade sessions")
            
            # Publish events for each active session
            for session in active_sessions:
                trade_session_id = str(session['id'])
                
                for instrument in eligible_instruments:
                    try:
                        # Publish the eligible instrument event using standardized format
                        message_id = self.event_publisher.publish_eligible_instrument(
                            trade_session_id=trade_session_id,
                            instrument_data=instrument,
                            scanner_type=scanner_type
                        )
                        
                        if message_id:
                            log(f"Published eligible instrument: {instrument['trading_symbol']} for session {trade_session_id} - Message ID: {message_id}")
                        else:
                            log(f"Failed to publish eligible instrument: {instrument['trading_symbol']} for session {trade_session_id}", level="warning")
                            
                    except Exception as e:
                        log(f"Error publishing eligible instrument {instrument.get('trading_symbol', 'unknown')} for session {trade_session_id}: {str(e)}", level="error")
        
        except Exception as e:
            log(f"Error fetching active trade sessions: {str(e)}", level="error")
    