from trade_management_unit.lib.common.EnvFile import EnvFile
from django.shortcuts import HttpResponse, render
from django.http import JsonResponse
import json
from django.forms.models import model_to_dict
from django.db.models import Q
from django.core.exceptions import FieldError
from django.http import JsonResponse
from trade_management_unit.lib.Portfolio.Portfolio import Portfolio




def get_holdings(request,*args,**kwvrgs):
    query_paramas  =  request.GET
    folio = Portfolio()
    response = folio.get_holdings(query_paramas)
    return JsonResponse(response,status=200, content_type='application/json')


def get_positions(request,*args,**kwvrgs):
    query_paramas  =  request.GET
    folio = Portfolio()
    response = folio.get_positions(query_paramas)
    return JsonResponse(response,status=200, content_type='application/json')



def place_order(request,*args,**kwvrgs):
    query_paramas  =  request.GET


def get_daily_all_orders(request,*args,**kwvrgs):
    pass
    # Retrieve the list of all orders (open and executed) for the day
    # query_paramas  =  request.GET
    # folio = Portfolio()
    # response = folio.get_daily_all_orders(query_paramas)
    # return JsonResponse(response,status=200, content_type='application/json')



def get_daily_exicuted_orders_(request,*args,**kwvrgs):
    # Retrieve the list of all orders (open and executed) for the day
    query_paramas  =  request.GET


def get_orders(request,*args,**kwvrgs):
    # Retrieve the history of a given order
    query_paramas  =  request.GET
    folio = Portfolio()
    response = folio.get_orders(query_paramas)
    return JsonResponse(response,status=200, content_type='application/json')



def get_orders_trades(request,*args,**kwvrgs):
    # Retrieve the trades generated by an orderx
    query_paramas  =  request.GET
    folio = Portfolio()
    response = folio.get_orders(query_paramas)
    return JsonResponse(response,status=200, content_type='application/json')

def get_order_history(request,*args,**kwvrgs):
    # Retrieve the trades generated by an orderx
    query_paramas = request.GET
    folio = Portfolio()
    response = folio.get_order_history(query_paramas)
    return JsonResponse(response,status=200, content_type='application/json')

def place_order(request,*args,**kwvrgs):
    # Retrieve the trades generated by an orderx
    query_paramas = request.GET
    folio = Portfolio()
    response = folio.place_order(query_paramas)
    return JsonResponse(response,status=200, content_type='application/json')



