"""
Django settings for ats_base project.

Generated by 'django-admin startproject' using Django 4.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for security, fallback to development key
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 
    'django-insecure-6@b!tg_a%y_-i#y#x89keub36fu6^fbx=-3a8d^4sa%y_qr)yf'  # Development fallback
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Disable automatic slash appending to prevent trailing slash issues
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'channels',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'trade_management_unit',
    'ats_gateway',
    'integration_service',
    'scanning_service',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'ats_gateway.middleware.jwt_auth_middleware.JWTAuthMiddleware',
]

ROOT_URLCONF = 'ats_base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'ats_base.wsgi.application'
ASGI_APPLICATION = 'ats_base.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get('REDIS_HOST', 'localhost'), int(os.environ.get('REDIS_PORT', 6379)))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.environ.get('DATABASE_NAME', 'ats_db'),
        'USER': os.environ.get('DATABASE_USER', 'root'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashers - Explicit bcrypt configuration for consistency
# This ensures all password hashing uses bcrypt, matching our custom UserManager implementation
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher', 
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Fallback for existing data
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',  # Additional fallback
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# URL path for serving static files (CSS, JavaScript, images, etc.)
STATIC_URL = '/static/'

# URL path for serving media files (uploaded files, user-generated content, etc.)
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'ats_gateway.User'

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = False  # Changed to False for better security with credentials
CORS_ALLOW_CREDENTIALS = True  # Allow credentials in CORS requests

# Specific origins for frontend
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:18000',  # Add backend URL in case of self-referencing requests
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'Authorization',
    'Content-Type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-trace-id',
]

# Additional CORS settings for better compatibility
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Revert to simpler cookie configuration that works with HTTP
SECURE_COOKIES = False  # Must be False for HTTP in development

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logfile.log'),
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'DEBUG',
    },
}

# Service URLs Configuration
# These URLs are used for inter-service communication in the microservices architecture
INTEGRATION_SERVICE_URL = os.environ.get('INTEGRATION_SERVICE_URL', 'http://localhost:8000/integration_service')
TMU_SERVICE_URL = os.environ.get('TMU_SERVICE_URL', 'http://localhost:8000/tmu')
SCANNING_SERVICE_URL = os.environ.get('SCANNING_SERVICE_URL', 'http://localhost:8000/scanning_service')

# Redis Configuration
# Used for message queuing, caching, and inter-service communication
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
REDIS_DB = int(os.environ.get('REDIS_DB', 0))

# Redis Stream Configuration
# Stream names for different event types
REDIS_STREAM_SCANNING_QUEUE = os.environ.get('REDIS_STREAM_SCANNING_QUEUE', 'scanning_queue')
REDIS_STREAM_INITIATION_QUEUE = os.environ.get('REDIS_STREAM_INITIATION_QUEUE', 'initiation_queue')
REDIS_STREAM_SCANNER_STATUS = os.environ.get('REDIS_STREAM_SCANNER_STATUS', 'scanner_status_stream')

# Service Communication Timeouts (in seconds)
SERVICE_REQUEST_TIMEOUT = int(os.environ.get('SERVICE_REQUEST_TIMEOUT', 30))
SERVICE_CONNECT_TIMEOUT = int(os.environ.get('SERVICE_CONNECT_TIMEOUT', 10))

# Redis Connection Configuration
REDIS_SOCKET_TIMEOUT = int(os.environ.get('REDIS_SOCKET_TIMEOUT', 5))
REDIS_SOCKET_CONNECT_TIMEOUT = int(os.environ.get('REDIS_SOCKET_CONNECT_TIMEOUT', 5))
REDIS_HEALTH_CHECK_INTERVAL = int(os.environ.get('REDIS_HEALTH_CHECK_INTERVAL', 30))

# Consumer Configuration
REDIS_CONSUMER_BATCH_SIZE = int(os.environ.get('REDIS_CONSUMER_BATCH_SIZE', 10))
REDIS_CONSUMER_TIMEOUT = int(os.environ.get('REDIS_CONSUMER_TIMEOUT', 1000))  # milliseconds
