# Generated by Django 3.2 - Create User Broker Credentials Table

from django.db import migrations, models
import django.utils.timezone
from django_mysql.models import EnumField
from django.core.validators import MinLengthValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # No dependencies since this is foundational table
    ]

    operations = [
        # Create UserBrokerCredential table
        migrations.CreateModel(
            name='UserBrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                
                # User reference - UUID field referencing User.public_id
                ('user_id', models.UUIDField(
                    blank=False, 
                    db_index=True,
                    help_text="References User.public_id"
                )),
                
                # Broker configuration
                ('broker_name', EnumField(
                    choices=[("zerodha", "zerodha")],
                    default="zerodha",
                    db_index=True,
                    help_text="Broker name for integration"
                )),
                
                # API credentials - encrypted in practice
                ('api_key', models.CharField(
                    max_length=255, 
                    blank=False,
                    validators=[MinLengthValidator(10)],
                    help_text="Broker API key"
                )),
                ('api_secret', models.CharField(
                    max_length=255, 
                    blank=False,
                    validators=[MinLengthValidator(10)],
                    help_text="Broker API secret"
                )),
                
                # Token management
                ('access_token', models.CharField(
                    max_length=512, 
                    blank=True, 
                    null=True,
                    help_text="Current access token from broker"
                )),
                ('refresh_token', models.CharField(
                    max_length=512, 
                    blank=True, 
                    null=True,
                    help_text="Refresh token for access token renewal"
                )),
                ('public_token', models.CharField(
                    max_length=512, 
                    blank=True, 
                    null=True,
                    help_text="Public token from broker (encrypted)"
                )),
                
                # Credential status
                ('status', EnumField(
                    choices=[
                        ("pending_verification", "pending_verification"),
                        ("active", "active")
                    ],
                    default="pending_verification",
                    db_index=True,
                    help_text="Current status of the credential"
                )),
                
                # Account management
                ('is_default', models.BooleanField(
                    default=False,
                    db_index=True,
                    help_text="Whether this is the default credential for the user"
                )),
                
                # Validation and monitoring
                ('last_refreshed_at', models.DateTimeField(
                    blank=True, 
                    null=True,
                    help_text="When the credentials were last refreshed"
                )),
                ('validation_error', models.TextField(
                    blank=True, 
                    null=True,
                    help_text="Last validation error message if any"
                )),
                ('last_used_at', models.DateTimeField(
                    blank=True, 
                    null=True,
                    help_text="When the credentials were last used for trading"
                )),
                
                # Kite specific fields
                ('kite_user_id', models.CharField(
                    max_length=50, 
                    blank=True, 
                    null=True,
                    help_text="User ID from Kite/Zerodha (e.g. OOD246)"
                )),
                
                # Metadata
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Broker Credential',
                'verbose_name_plural': 'User Broker Credentials',
                'db_table': 'user_broker_credentials',
                'ordering': ['user_id', '-is_default', 'broker_name'],
            },
        ),

        # Add performance indexes and constraints
        migrations.RunSQL(
            """
            -- Primary indexes for user_broker_credentials
            CREATE INDEX idx_usr_broker_user_id ON user_broker_credentials(user_id);
            CREATE INDEX idx_usr_broker_name ON user_broker_credentials(broker_name);
            CREATE INDEX idx_usr_broker_status ON user_broker_credentials(status);
            CREATE INDEX idx_usr_broker_default ON user_broker_credentials(is_default);
            CREATE INDEX idx_usr_broker_created ON user_broker_credentials(created_at);
            CREATE INDEX idx_usr_broker_used ON user_broker_credentials(last_used_at);
            CREATE INDEX idx_usr_broker_kite_user ON user_broker_credentials(kite_user_id);
            
            -- Composite indexes for common query patterns
            CREATE INDEX idx_usr_broker_user_name ON user_broker_credentials(user_id, broker_name);
            CREATE INDEX idx_usr_broker_user_stat ON user_broker_credentials(user_id, status);
            CREATE INDEX idx_usr_broker_user_def ON user_broker_credentials(user_id, is_default);
            """,
            reverse_sql="""
            -- Drop primary indexes
            DROP INDEX IF EXISTS idx_usr_broker_user_id;
            DROP INDEX IF EXISTS idx_usr_broker_name;
            DROP INDEX IF EXISTS idx_usr_broker_status;
            DROP INDEX IF EXISTS idx_usr_broker_default;
            DROP INDEX IF EXISTS idx_usr_broker_created;
            DROP INDEX IF EXISTS idx_usr_broker_used;
            DROP INDEX IF EXISTS idx_usr_broker_kite_user;
            
            -- Drop composite indexes
            DROP INDEX IF EXISTS idx_usr_broker_user_name;
            DROP INDEX IF EXISTS idx_usr_broker_user_stat;
            DROP INDEX IF EXISTS idx_usr_broker_user_def;
            """
        ),

        # Add unique constraints - MySQL compatible version
        migrations.RunSQL(
            """
            -- Ensure API key uniqueness per broker (to prevent credential sharing)
            CREATE UNIQUE INDEX idx_usr_broker_uniq_key
            ON user_broker_credentials(broker_name, api_key);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_usr_broker_uniq_key;
            """
        ),
    ] 